### ISSUE TITLE
Homebridge plugin 

### ISSUE THREAD

**Issue by ojoaosemtil** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#10]
Hello!

This is not an issue, just a question...
Do you know about any kind of plugin like this to use with homebridge, to be compatible with HomeKit?

Or any other way to make it compatible to HomeKit?

Thank u in advance!

**Comment by chomupashchuk** [comment]
I do not know of any.
I have created dedicated API that can be integrated in any environment with python:
https://github.com/chomupashchuk/ariston-remotethermo-api

I see that someone downloaded API but i have no idea how it was used.
