### ISSUE TITLE
Error during setup of component aquaariston

### ISSUE THREAD

**Issue by lytryx** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#15]
Hi, I'm trying to install the custom component but it returns this error:

Logger: homeassistant.setup
Source: custom_components/aquaariston/aristonaqua.py:831
First occurred: 15 de marzo de 2021 20:11:28 (1 occurrences)
Last logged: 15 de marzo de 2021 20:11:28

Error during setup of component aquaariston
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/aquaariston/__init__.py", line 167, in setup
    polling=polling
  File "/home/homeassistant/.homeassistant/custom_components/aquaariston/__init__.py", line 134, in __init__
    logging_level="DEBUG",
  File "/home/homeassistant/.homeassistant/custom_components/aquaariston/aristonaqua.py", line 569, in __init__
    self._read_showers_temp()
  File "/home/homeassistant/.homeassistant/custom_components/aquaariston/aristonaqua.py", line 854, in _read_showers_temp
    self._write_showers_temp()
  File "/home/homeassistant/.homeassistant/custom_components/aquaariston/aristonaqua.py", line 831, in _write_showers_temp
    os.makedirs(self._store_folder)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/aqua_http_logs'

Any idea what the problem is? the user and password I use are correct, access to the web without problem.

thanks in advance

**Comment by chomupashchuk** [comment]
Based on an error the intergation attempts to create a folder (aqua_http_logs) but has no permission by OS. This folder is attempted to be created in 2 cases: 1) if storing files is set 2) if temperature mode is used in Velis for exmple, which is being simulated by the integration as an experimental feature, as the boiler works only with number of showers.
So either avoid using those functions or create folder manually (if I remeber correctly it's created within /config folder) and give full permission to it.

**Comment by lytryx** [comment]
Thank you so much for your quick response and for sharing your work!
I have tried with what you indicate but I cannot find the "config" folder .. where is it supposed to be?

thanks again

**Comment by chomupashchuk** [comment]
config folder is basically a folder, in which you keep `configuration.yaml` and `custom_components` folder.
I have no idea which environment you use, so it might differ otherwise (for example I use docker container on my Linux server, where I mount config folder to the folder of my choosing, while HASSIO has it's own structure etc.)

**Comment by lytryx** [comment]
Hi, thanks again for your help !
I use Home Assistant Core mounted on Raspbian, so I understand that my config folder is: /home/homeassistant/.homeassistant
I have created the folder there with full permissions, but it doesn't work... the same error keeps getting.

I don't know what else to try.. Any idea I could try? I'm very interested in integrating the component, I find it very interesting.

thanks in advance

**Comment by chomupashchuk** [comment]
in __init__.py you may try uncommenting (remove `#`) and changing folder path (path is from within container):           #store_folder="/config/aquaariston_http_data",

I have HA Core on Synology NAS and I do not have boiler supporting this integration, so much was not tested regarding configuration.

**Comment by lytryx** [comment]
perfect ! it works now !! Thank you very much for your help and for your great work !!

thank you very much again and good job really

**Comment by chomupashchuk** [comment]
Just a question: what did you changed folder to?

**Comment by lytryx** [comment]
Hi, I have changed exactly what you told me: in the line #store_folder="/config/aquaariston_http_data", I have deleted (#), and I have changed the path to: store_folder="/home/homeassistant/.homeassistant/aqua_http_logs"
that's all

**Comment by chomupashchuk** [comment]
now parameter "path" in configuration.yaml should force new values.

For some reason I cant't understand why "/home/homeassistant/.homeassistant/" should be used, as inside a container "/config" should be a valid option and why there was an issue with automated path detection. Anyways it is what it is.
