### ISSUE TITLE
Is  antilegionella_set_temperature sensor correct?

### ISSUE THREAD

**Issue by dtalens** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#16]
Is  antilegionella_set_temperature sensor correct? Doesn't it correspond to the maximum temperature you can indicate on the thermo?

According to the user manual, the temperature of anti-legionella function is approximately 60 ºC.
In addition, ariston aqua app indicates max. temperature referring to the maximum you can reach this apliance.
![image](https://user-images.githubusercontent.com/6631832/113788425-2b49fb00-973d-11eb-911a-c8656ae1a1cd.png)

![image](https://user-images.githubusercontent.com/6631832/113789437-63523d80-973f-11eb-8ade-737030573284.png)

On the first start of the device it had indicated 40 ºC but has risen to 65 ºC as anti-legionella function is activated but maximum temperature was set at 80 ºC therefore refers to the maximum temperature of the device. Or maybe I'm wrong.
My thermo model is Ariston Velis Wifi 100l

Thanks for create this integration!

**Comment by chomupashchuk** [comment]
I do not remember the details as I my boiler does not support this specific integration. The vale is fetched from "MedMaxSetpointTemperature" key in a specific request: 
f"{self._url}/api/v2/velis/{self._boiler_str}PlantData/{self._plant_id}/plantSettings?wheType=Med&appId=com.remotethermo.velis"

Maybe there is something incorrect, but I cannot verify anything myself without the equipment. There is no documentation on REST requests and responses, so we have what I was able to understand from provided data.
You may check the request data by setting store_config_files for implemented requests or connect phone (I used fiddler proxy) and check other requests if reported values is correct or not and compare it with the phone app.

**Comment by dtalens** [comment]
I have verified that indeed when I modifyk maximum temperature with phone app the value of antilegionella_set_temperature sensor changes.
