### ISSUE TITLE
Required temperature no changes in boiler

### ISSUE THREAD

**Issue by dtalens** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#17]
Hi again,

If I change temperature from HA it does not produce any change in the boiler or in the phone app. If the temperature changes from the phone app it also does not change to HA. 

I am testing and reviewing generated files in the aquaariston_data_http folder. If I change temperature from the phone app the file "data_ariston_get_main.json" is updated to the new data but in the frontend it does not change.
Temperature from phone app: 56 ºC
`/config/aquaariston_http_data/data_ariston_get_main.json`
`{"gw": "***************", "on": true, "mode": 1, "temp": 50.0, "procReqTemp": 56.0, "reqTemp": 56.0, "antiLeg": false, "heatReq": true, "eco": false, "rmTm": "00:35:00", "avShw": 2, "pwrOpt": false}`

Thanks for your time

**Comment by chomupashchuk** [comment]
Few questions:
1. When changing temperature via phone app did you wait up to few minutes in HA (did you check timestamp for mentioned file)? - it takes some time for HA to sync as unlike Ariston app which sends request when specific page is reloaded here I use periodic requests with set period that cashed relatively few connection events, so it might take time.
2. When changing temperature via HA did you reload page on phone app in about 10-15 seconds?

I do not have a boiler using this app nor I get any funding for this, so I do not want to look into code unless there is definitely a fault and I have time.
If there is fault I'll have a look into code and If I won't be able to find I'll probably need credentials to set traces to figure out which part does not work (from experience I had to add multiple logging cases to identify problematic place by multiple attempts and sending new file versions and waiting replies with logs I would consider a waste of my time (it is an option if it is potentially 1-2 times, not 5-15)).

So at first please confirm if there is actually a fault, if it is a fault, then I shall have code review, and if it won't help, I would need credentials to pinpoint the issue.

**Comment by dtalens** [comment]
> 1. When changing temperature via phone app did you wait up to few minutes in HA (did you check timestamp for mentioned file)? - it takes some time for HA to sync as unlike Ariston app which sends request when specific page is reloaded here I use periodic requests with set period that causes relatively few connection events, so it might take time.
> 2. When changing temperature via HA did you reload page on phone app in about 10-15 seconds?

1. Yes, I waited a while and checked time stamp.
2.  Yes
```
/config/aquaariston_http_data/data_ariston_get_main.json
{"gw": "XXXXXXXX", "on": true, "mode": 1, "temp": 48.0, "procReqTemp": 52.0, "reqTemp": 52.0, "antiLeg": false, "heatReq": true, "eco": false, "rmTm": "00:40:00", "avShw": 1, "pwrOpt": false}
```
Required temperature in phone app was set at 52 ºC but required temperature in hassio was set at 48 ºC.

```
/config/aquaariston_http_data/required_shower_temperature.json
{"required_temperature": 48.0, "showers_mode": "temperature"}
```
If you make any changes I can test it. Thanks!

**Comment by chomupashchuk** [comment]
The Velis boiler I based integration on did not use setting of temeparture directly but used number of showers (each additional shower stepped required temperature by multiple degrees). It caused additional logic, which stores/reads reuired temperature from dedicated file to tune number of showers. From what I understand in your Velis model you set temepartures directly.

If that is the case, you may try:
1) changing boiler type to "lydos" (not 'lydos_hybrid'), which shares a lot of data with Velis (including requests, which differ for lydos_hybrid) but works with temepartures directly.
2) if first step does not help, you may try replacing python file (also change extension to .py), which is potential workaround, which breaks logic for shower-based Velis so it is only a prototype to pinpoint the issue.
[aristonaqua.txt](https://github.com/chomupashchuk/ariston-aqua-remotethermo-home-assistant/files/6330985/aristonaqua.txt)

**Comment by dtalens** [comment]
> changing boiler type to "lydos" (not 'lydos_hybrid'), which shares a lot of data with Velis (including requests, which differ for lydos_hybrid) but works with temepartures directly.

It's working with changing boiler type to "lydos", thanks. 
Testing with "velis" type: Required shower requests do not work either.

**Comment by dtalens** [comment]
Version 1.0.35 is working properly with "velis" option configured.
