### ISSUE TITLE
Required showers and time left to heat not displaying properly

### ISSUE THREAD

**Issue by dtalens** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#19]
Required showers are always shown at zero except momentarily when aqua service is called to increase them.
![image](https://user-images.githubusercontent.com/6631832/116737953-200f8580-a9f2-11eb-8907-421e3c43d9b7.png)

Also time left to heat no displaying correctly, show this error:
![image](https://user-images.githubusercontent.com/6631832/116738080-47fee900-a9f2-11eb-8ba4-043bd1befff0.png)
Translate: Invalid timestamp

**Comment by chomupashchuk** [comment]
Lately there were changes with unique ids which causes duplication of entities. As result old entities have to be deleted and new might require renaming (2 at the end).
Did it work in previous versions? Just want to know if it could be the case.
I do not have a boiler supporting this integration, so I can't check things myself that makes maintenance rather a nightmare.

**Comment by chomupashchuk** [comment]
Is it possible to get more information?
It might be the last update i'll consider for the integration as my boiler works with different integration and I have no possibility to troubleshoot myself nor test new solutions. It is frustrating and I plan to park the updates of this integration.

**Comment by chomupashchuk** [comment]
Which model do you use?
In Velis model I see that Ariston server reports 0 showers (that I got my hands on), which seems strange.

**Comment by dtalens** [comment]
lMy boiler is Ariston Velis wifi but I have to indicate "lydos" in aqua integration for it to work properly as I mentioned in deleted issue. I can provide you with the information you need within my means.

I don't know if it will help you but I will send you complete folder "aquaariston_http_data" (I deleted my boiler ID).

[aquaariston_http_data.zip](https://github.com/chomupashchuk/ariston-aqua-remotethermo-home-assistant/files/6423060/aquaariston_http_data.zip)

**Comment by chomupashchuk** [comment]
From the files I can see that number of showers is being read successfully (1 as average and 0 as required), and values are being reported by the server. Setting of value is a bit tricky as integration shows new value (as expected one) meanwhile the integration actually attempts to change it in the server. So if change fails in the server then temporary wanted value is shown while change attempts are being made. "lydos" was not designed to change number of showers.

Now in logs I see file `data_ariston_set_temperature_500_error.txt` and inside it shows that request is not supported. It means that integration does not support temperature setting but rather number of showers (unless something changed with supported requests), so seems like in your case it should be boiler type "velis".
In closed ticket you write that it works with lydos and then velis types, and now it's lydos again? So which one are you actually using?
