### ISSUE TITLE
Hassio restart

### ISSUE THREAD

**Issue by Nemesis24** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#2]
Thanks for this nice job.

When hassio restart, the water heater take one shower more.
I want to have 2 showers in manual mode, but if hassio restart like update i've got 3 showers on the water heater.

Thanks a lot.

**Comment by chomupashchuk** [comment]
Not sure what might be happening in your case. Home Assistant uses temperatures in water_heater component, which is not the same as showers for some models (it is possible to read set temperature, but setting is possible only by means of showers). I have added code as "automatic" mode, which should have changed amount of showers based on requested temperature (increase amount of showers if temperature is not reached and decrease if it is reached), but i did note have possibility to test it (two guys with different boilers gave me access to their boilers temporary for initial tests during implementation).

Integration automatically switches how amount of showers is being controlled (if within the service in HA amount of showers is set, it should disable "automatic" control amount of showers based on temperature, but changing temperature in service or as part of water_heater enables this "automatic mode"). 
So please try changing number of showers via service to disable possible use of "automatic" mode, which might be working not so well. Without this "automatic" mode the integration should simply read the data unless number of showers changed manually. There is sensor "temperature_mode" which can be used to view if indeed it is the problem that i suspect.
Note that i have boiler, which does not support this integration at all, so i can't test it. Also i have my hands full with changes at work and i have a lot less free time to spend on this (i make changes in cases it is not too time consuming).

**Comment by chomupashchuk** [comment]
No information to proceed with investigation
