### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by Nemesis24** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#22]
Hello just for saying that's a great job, could you integrate it via hacs to be more wonderful. 
Thanks for all and Merry christmas with hot showers !!!

**Comment by surenz** [comment]
It is integrated. 
Just add the repository manually via the three dots at top right (Custom repositories) and it will install correctly and even the last update shows up since yesterday.

Regards.

**Comment by Nemesis24** [comment]
Ho Ho Ho !!!  you arrived like the fat bearded man !! This is excellent !!! 
I don't know this functionnality.
Thank you very much !!!
