### ISSUE TITLE
Problem with Login 

### ISSUE THREAD

**Issue by ramon2k10** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#25]
Hi yesterday there was a change in two files to accommodate the login change. I have downloaded those two files ("aristonaqua.py" and "manifest.json") but when restarting I get the following errors.

[2835842528] The system cannot restart because the configuration is not valid: Component error: aquaariston - Integration 'aquaariston' not found.
0:07:31 – (ERROR) Home Assistant WebSocket API - el mensaje se produjo por primera vez a las 0:07:21 y aparece 2 veces
The system cannot restart because the configuration is not valid: Component error: aquaariston - Integration 'aquaariston' not found.
0:07:31 – (ERROR) Home Assistant Core Integration - el mensaje se produjo por primera vez a las 0:07:21 y aparece 2 veces

**It is possible that something needs to be modified in the configuration.yaml file?**

This is my 

aquaariston:
  username: username
  password: password
  type: "velis"
  #path: "/home/homeassistant/.homeassistant/aqua_http_data" # Forces new path for storing files. SET NEW VALUES IF "/config" IS NOT CORRECT
  switches:
    - eco                             # switches ECO mode
    - power                           # switches power
  binary_sensors:
    - antilegionella                  # indicates antilegionella status
    - changing_data                   # indicates ongoing configuration on server by the API
    - eco                             # indicates ECO mode status
    - heating                         # indicates ongoing heating
    - online                          # indicates API online status
    - power                           # indicates power status
    - update                          # indicates API update
  sensors:
    - antilegionella_set_temperature  # antilegionella temperature
    - current_temperature             # current temperature
    - energy_use_in_day               # energy use in last day
    - energy_use_in_month             # energy use in last week
    - energy_use_in_week              # energy use in last month
    - energy_use_in_year              # energy use in last year
    - errors                          # errors
    - mode                            # manual or time program mode
    - remaining_time                  # remaining time for heating
    - required_showers                # required amount of showers (might not work on all models)
    - required_temperature            # required temperature (simulated by API itself for some models)
    - showers                         # estimated amount of average showers
    - temperature_mode                # indicates if required temeparture is based on required temperature or required showers
    -     - time_program                    # time program schedule
  selector:
    - mode                            # boiler mode selector

I'll appreciate if you could support me on this problem
Regards

**Comment by YgRex2020** [comment]
Hey! I have the same problem. 
<custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x7f5946205b20> Authentication login error

**Comment by YgRex2020** [comment]
> Hey! I have the same problem. <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x7f5946205b20> Authentication login error

Everything is fine. I just needed to update the integration. Thank you!
