### ISSUE TITLE
Every day errors in HASSIO logs

### ISSUE THREAD

**Issue by krzysiek2788** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#3]
Hi,
Every day I have this kind of errors in Hssio logs. I have Ariston Velis Wi-Fi 100L if that helps:

> Logger: custom_components.aquaariston.aristonaqua
> Source: custom_components/aquaariston/aristonaqua.py:1090
> Integration: aquaariston
> First occurred: 4 października 2020, 21:26:25 (11 occurrences)
> Last logged: 7:14:38
> 
> <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x7f63ae4e7be0> _get_main Problem reading data
> <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x7f63ae4e7be0> _get_version Problem reading data
> <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x7f63ae4e7be0> _get_showers Problem reading data
> <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x7f63ae4e7be0> _get_error Problem reading data

**Comment by chomupashchuk** [comment]
It is normal to get such issues even in normal conditions. Integration logs all issues including web requests timeouts, which occasionally happen (during server errors or internet issues their amount increases a lot).

So if sensors are reported then it is not an issue.
