### ISSUE TITLE
HomeAssistant-> Google home entity

### ISSUE THREAD

**Issue by b0c1** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#4]
Thank's that awesome plugin. 
I have only one issue. I try to add the entity to the home assistant integration but only the eco mode and power switch are available. 
I need to see/query the current/target temperature, time to heat up, etc...

Can you add these entities to available to google home integration (I have a node-red temperature (sensor) entity from my orange pi and it's visible in the home assistant -> google home integration)

Thanks

**Comment by b0c1** [comment]
I think the sensor entities device class not set correctly (not the icon)
https://www.home-assistant.io/integrations/sensor/
https://www.home-assistant.io/integrations/binary_sensor/

This is my orange pi temperature sensor in developer tools page:
![image](https://user-images.githubusercontent.com/339029/97632059-413aed80-1a32-11eb-93f2-d793823256d6.png)

And this is the Ariston sensor:
![image](https://user-images.githubusercontent.com/339029/97632143-66c7f700-1a32-11eb-949e-55bdad5a5a3e.png)

**Comment by chomupashchuk** [comment]
Sensor class is optional.

Sensors until recently could not be added to Google Home so i have not checked the details. Are you saying that without specified device class google does not recognize temperatures? Does it work for your orangepi_temperature? Did you try to customize ariston sensor using HA customization?

I have exposes only climate entity (which includes current temperature) to Google Home as sensors were not supported when i started work on the integration.

**Comment by chomupashchuk** [comment]
No reply for a long time
